import "./globals.css";
import { cn } from "@/lib/utils";
import connectDB from "@/db/connectDB";
import { Toaster } from "react-hot-toast";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDB();
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children} <Toaster />
      </body>
    </html>
  );
}
